### ISSUE TITLE
Domain http://robo.li/ is not available

### ISSUE THREAD

**Issue by Sweetchuck** [consolidation/robo#1146]
### Steps to reproduce

1. Go to http://robo.li/

### Expected behavior

A normal page load.

### Actual behavior

ERR_NAME_NOT_RESOLVED

### System Configuration

Linux. Chromium and FireFox.

---

@greg-1-anderson: Maybe the domain is expired and a renewal is required.

**Comment by greg-1-anderson** [comment]
@DavertMik I don't remember what I did to renew robo.li last year. If you'd like me to maintain it every year, we should transfer it to my registrar so that I see the expiration notices. I'll need instructions again for renewing this year. I think I'm still connected to your slack instance on my other computer, so you can DM me there.

**Comment by benlamptey-gocity** [comment]
Would love for this to be solved asap! @DavertMik @greg-1-anderson anything I can do to help?

**Comment by benlamptey** [comment]
any luck on this anyone ?

**Comment by DavertMik** [comment]
@greg-1-anderson I see its still on my account
and is restorable

**Comment by benlamptey** [comment]
thanks for getting it back up !!

**Comment by greg-1-anderson** [comment]
Thanks, @DavertMik. If you would like me to renew it every year, let's transfer it to my registrar. We might have to wait a while to do that, there's a black-out period for transfers after recovery, if I recall correctly.

**Comment by DavertMik** [comment]
Yeah, let's connect next year about this
I thought It was transferred....
