### ISSUE TITLE
SSH: Remote server getting commands with simple quote at the end of the command name (or argument)

### ISSUE THREAD

**Issue by vluzrmos** [consolidation/Robo#133]
On windows development machine, when a run a command to do ssh tasks to the server (running on ubuntu) says: 
the "command'" does exists! (note the single quote at the end)

So, I edited the line 187 on codegyre\robo\src\Task\Remote\Ssh.php
```
return sprintf("ssh{$sshOptions} {$hostSpec} \"{$command}\"");
```
And now it works!

**Comment by boedah** [comment]
I think this is due to the fact that the shell escaping is done on the machine executing Robo. 

Which is not compatible between Windows and others.  (never thought that someone would use the SSH task on Windows ;-)

I see a few options :

* escape automatically according to the target machine type
* provide an option to the task "os" or the like, to escape accordingly 
* provide an option to disable escaping 
* let the user escape herself (maybe provide methods for that) 

My preference would be third option.

**Comment by boedah** [comment]
Just saw #137, and this would change from weak to strong quoting on Linux and e.g. do parameter expansion, which may be an unwanted side effect and probably break existing scripts.

Maybe the quote character should be an option?
Like:

```php
$this->taskSshExec('remote.example.com')
    ->commandQuoteCharacter('"')
    ->exec('foo')
    ->run();
```

Therefore the user can decide herself.

PS: by looking at the code I saw no http://php.net/manual/en/function.escapeshellarg.php is used.
So my comment above is irrelevant...

**Comment by boedah** [comment]
Maybe #157 (using ProcessUtils::escapeArgument) can also be helpful here?
As we cannot test in Travis on Windows, maybe first some real tests should be created for Linux?

What comes to my mind is really connecting to the Travis build machine itself (via localhost) and executing various commands to check:

* concatenation of commands
* commands with
 * single quotes
 * double quotes (and making sure shell escaping
 * double quotes and shell variables (and making sure the expansion is done on the remote host)
* ...?

**Comment by greg-1-anderson** [comment]
Closed due to lack of activity. Escape quoting has been enhanced a bit; there is some chance this might work better now. Try again with latest 1.x Robo.
