### ISSUE TITLE
Implement Fast Clone in VCS Git Stack

### ISSUE THREAD

**Issue by javigomez** [consolidation/Robo#161]
Every time I execute my tests I need to clone several repositories to get the latest files. And I found this way to clone repos really fast:

```
git clone -b ${branch} --single-branch --depth 1 ${repository} ${toFolder}
```

This command just brings the branch and forgets all the repo history. Is really fast.

Do you have any suggestion about how can we implement it here?:
https://github.com/Codegyre/Robo/blob/master/src/Task/Vcs/GitStack.php#L35-L45

**Comment by boedah** [comment]
Just FYI: `--single-branch` is default if `--depth` is used.
So a `$depth` parameter to the clone methode would suffice (+ `$branch`).

**Comment by javigomez** [comment]
Good point, but still you can't pass args to that Task:

```
        $this->taskGitStack()
            ->cloneRepo($repository, $toFolder)
            ->arg('--depth 1');
```

Like you do in other Tasks

![screen shot 2015-04-21 at 18 39 57](https://cloud.githubusercontent.com/assets/1375475/7257327/40a73b54-e855-11e4-965a-a6b3bb28da63.png)

**Comment by burzum** [comment]
There is something related I would like to add to this discussion. If you look at https://github.com/Codegyre/Robo/blob/master/src/Task/Testing/PHPUnit.php you'll notice that in this task option() is used instead of arg() but they do the same thing.

I think this should be unified across the tasks. Many of them are just wrappers around other console tools and need to pass args and parse output.

**Comment by greg-1-anderson** [comment]
Closed due to lack of activity.
