### ISSUE TITLE
Global stopOnFail(true) should be overrideable with local stopOnFail

### ISSUE THREAD

**Issue by c33s** [consolidation/Robo#264]
having set the global `stopOnFail()` to `false` should be overrideable

```
/**
 * RoboFile constructor.
 */
public function __construct()
{
	$this->stopOnFail(true);
}
```
the `stopOnFail(false)` in the `taskExecStack()` doesn't prevent the stop.
```
$this->taskExecStack()
	->stopOnFail(false)
	->exec('my failing command')
	->run();
```

**Comment by greg-1-anderson** [comment]
Note that `stopOnFail` for stack-based commands has a completely separate function than Result::stopOnFail.  If Result::stopOnFail() is set to `true`, that takes precedence over the local stopOnFail functions. This is by design.

See also the new "Collections" classes (#271) as an alternative to Result::stopOnFail(), and also please see #270.
