### ISSUE TITLE
Install fails on PHP 5.5

### ISSUE THREAD

**Issue by jjok** [consolidation/Robo#483]
### Steps to reproduce

`composer install`

### Expected behavior

Composer installs dependencies. `composer.json` says that PHP 5.5 is supported, but the dev dependencies require PHP 5.6.

### Actual behavior

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.jso
n. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpunit/php-code-coverage 4.0.1 -> satisfiable by
 phpunit/php-code-coverage[4.0.1].
    - phpunit/php-code-coverage 4.0.1 requires php ^5.6 || ^7.0 -> your PHP vers
ion (5.5.30) does not satisfy that requirement.
  Problem 2
    - Installation request for phpunit/phpunit 5.5.6 -> satisfiable by phpunit/p
hpunit[5.5.6].
    - phpunit/phpunit 5.5.6 requires php ^5.6 || ^7.0 -> your PHP version (5.5.3
0) does not satisfy that requirement.
  Problem 3
    - Installation request for phpunit/phpunit-mock-objects 3.3.1 -> satisfiable
 by phpunit/phpunit-mock-objects[3.3.1].
    - phpunit/phpunit-mock-objects 3.3.1 requires php ^5.6 || ^7.0 -> your PHP v
ersion (5.5.30) does not satisfy that requirement.
  Problem 4
    - Installation request for sebastian/code-unit-reverse-lookup 1.0.0 -> satis
fiable by sebastian/code-unit-reverse-lookup[1.0.0].
    - sebastian/code-unit-reverse-lookup 1.0.0 requires php >=5.6 -> your PHP ve
rsion (5.5.30) does not satisfy that requirement.
  Problem 5
    - Installation request for sebastian/object-enumerator 1.0.0 -> satisfiable
by sebastian/object-enumerator[1.0.0].
    - sebastian/object-enumerator 1.0.0 requires php >=5.6 -> your PHP version (
5.5.30) does not satisfy that requirement.
  Problem 6
    - Installation request for sebastian/resource-operations 1.0.0 -> satisfiabl
e by sebastian/resource-operations[1.0.0].
    - sebastian/resource-operations 1.0.0 requires php >=5.6.0 -> your PHP versi
on (5.5.30) does not satisfy that requirement.
  Problem 7
    - Installation request for sebastian/version 2.0.0 -> satisfiable by sebasti
an/version[2.0.0].
    - sebastian/version 2.0.0 requires php >=5.6 -> your PHP version (5.5.30) do
es not satisfy that requirement.
  Problem 8
    - phpunit/php-code-coverage 4.0.1 requires php ^5.6 || ^7.0 -> your PHP vers
ion (5.5.30) does not satisfy that requirement.
    - codeception/base 2.2.5 requires phpunit/php-code-coverage >=2.1.3 <5.0 ->
satisfiable by phpunit/php-code-coverage[4.0.1].
    - Installation request for codeception/base 2.2.5 -> satisfiable by codecept
ion/base[2.2.5].
```

### System Configuration

PHP 5.5.*

**Comment by jjok** [comment]
I asked Jordi and it looks like it's not possible to have different PHP version dependencies between `require` and `require-dev`.

https://twitter.com/jnthnjffris/status/793810779845824512

**Comment by greg-1-anderson** [comment]
@jjok Sorry for the inconvenience here. As you can [see from the tests](https://travis-ci.org/consolidation/Robo), Robo does in fact work on PHP 5.5.  The problem here is not the require-dev dependencies; they work on PHP 5.5 just fine. The real problem is that the composer.lock file includes dependencies that require PHP 5.5. To work around this in the `git clone`, `composer install` workflow, it should be sufficient to simply remove the composer.lock file and then run `composer update`; however, the `.travis.yml` file is a little more specific, and instead does this:
```
rm composer.lock; composer require --no-update "phpunit/php-code-coverage:~2"
```
The other implication here is that the Robo phar does not support PHP 5.5. Not sure what the best way forward is. PHP 5.5 is EOL, but I feel it is still widely enough used that we should continue supporting it for the time being. I don't think that we should build the composer.lock with `composer update --prefer-dist --prefer-lowest`, as that would mean that anyone running Robo off of the locked components would get older versions than available for our dependencies, which would probably be undesirable.  It might be a good idea to force `phpunit/php-code-coverage:~2` in the phar build so that the phar will build correctly. We should certainly improve the documentation to help folks still running on php 5.5 get started.

Note that if you require consolidation/robo as a dependency from a project that requires PHP 5.5, then everything will work fine.

**Comment by greg-1-anderson** [comment]
@DavertMik ^^

**Comment by greg-1-anderson** [comment]
Discussed with @DavertMik last night. We decided that the specific issue reported by the OP could be solved simply by removing the composer.lock file from the repository. This morning I am less inclined to do that; I think that a Composer pre-install script could detect the combination of php 5.5 + a composer.lock file + the wrong version of php-code-coverage, and remove the composer.lock file automatically. I'll give this a try and see if it works.

I'll also install php 5.5. and try the phar. If the php 5.5 requirement is limited to php-code-coverage, then in theory the phar should work fine.

**Comment by jjok** [comment]
Would it not have been enough to just add the `"phpunit/php-code-coverage": "~2|~4"` and do a `composer update`? Presumably you found the script was required too?

**Comment by greg-1-anderson** [comment]
@jjok Yes, the composer.json change + `composer update` would have been enough. However, folks are used to doing `git clone` + `composer install` on a new project.  The script allows this to work. Without the script, I felt there would be continuing confusion.

The composer.json change + removing composer.lock also would have worked. However, I didn't want to do that either, because I wanted typical usage (`git clone` + `composer install`) to use the same components that the maintainers last tested & wrote into the composer.lock file. With this protection, a bug in a dependency that manages to get into a stable release will break our tests, but will not break new installs. This gives us more time to find and correct problems before new users are impacted.
