### ISSUE TITLE
Example code for bootstrapping and running a command

### ISSUE THREAD

**Issue by elmpp** [consolidation/Robo#489]
This is more a request for a snippet/gist of code to demonstrate how one would run a command from another [symfony] command context? With the recent api changes the following has ceased to work and i'm having trouble reverse engineering the arguments to the new static Robe::Run method. 

If i'm missing anything in the docs, my apologies. This code here is what formerly would work well:

https://gist.github.com/elmpp/0f760a99338f4e016373356f5b2c8493

Many thanks

**Comment by greg-1-anderson** [comment]
In order to run a Robo command, you must ensure that the Robo Dependency Injection container is initialized.  If you're trying to do this from a Symfony Console application, the best thing to do is to read the document on [using Robo as a Framework](http://robo.li/framework/). If you follow this guide, you will be able to use annotated commands to define your Symfony Console commands. This is recommended, because it makes it easier to use the [output formatters](https://github.com/consolidation/output-formatters); however, it is not required. Just follow the instructions in [Using Your Own Dependency Injection Container with Robo](), and add your own Symfony Console commands to your Application object.

You could also follow this pattern with a Symfony application that was not a Symfony Console application; however, Robo was primarily intended to be used as a task runner; it may or may not meet the needs of other sorts of applications. If you do try something like this, please share your experiences and let us know what works and what does not.
