### ISSUE TITLE
robo init still throws errors about Robofile.php

### ISSUE THREAD

**Issue by daften** [consolidation/Robo#502]
### Steps to reproduce
Run robo init

### Expected behavior
It should generate the Robofile.php without errors

### Actual behavior
Some errors are shown in the output:
```
robo init
Requested RoboFile `/Users/blommedi/Downloads/robo.dev/RoboFile.php` is invalid, please provide valid absolute path to load Robofile
➜
➜   Robo is not initialized here. Please run `robo init` to create a new RoboFile
➜
  ~~~ Welcome to Robo! ~~~~
  RoboFile.php will be created in the current directory
  Edit this file to add your commands!
```

### System Configuration
Mac OS X 10.11.6 with PHP 5.6.25
robo installed through homebrew (phar is installed)

**Comment by angelxmoreno** [comment]
Seems to still be happening as of v1.1. The unexpected behavior, coupled with the lack of communication about this in the docs, yields a lack of confidence in the project. The very first thing I do to get started involves confusion and big red letters yelling at me. We should either address this in the docs or fix `\Robo\Runner` in some way like so:

Instead of
```php
if (!isset($commandFiles)) {
    $this->yell("Robo is not initialized here. Please run `robo init` to create a new RoboFile", 40, 'yellow');
    $app->addInitRoboFileCommand($this->roboFile, $this->roboClass);
    $commandFiles = [];
}
```
Have something like:
```php
if($this->getInput()->getFirstArgument() === 'init'){
    $this->say("Initializing a new RoboFile", 40, 'yellow');
    $app->addInitRoboFileCommand($this->roboFile, $this->roboClass);

    return false;
}

if (!isset($commandFiles)) {
    $this->yell("Robo is not initialized here. Please run `robo init` to create a new RoboFile", 40, 'yellow');

    return false;
}
```
I could submit a PR but it will take me a while to familiarize myself with the codebase a little deeper to know if this is the best solution.

**Comment by greg-1-anderson** [comment]
Take a look at #602 and see if the behavior there is closer to your expectations.
