### ISSUE TITLE
Confirmation on how rollback and completions work for Collections

### ISSUE THREAD

**Issue by jakenoble** [consolidation/Robo#544]
> $collection = $this->collectionBuilder();
> $collection->addTask(
>     $this->taskCodecept('vendor/bin/codecept')
>         ->dir('release/application')
>         ->test('functional')
>         ->configFile('src/AppBundle')
>         ->html("functional_output.html")
> )->run();
> 
> $collection->completion($this->complete());
> 
> $collection->rollback($this->rollback());
> 

Given the above code, if my tests fail I want `rollback()` to be called only and not `complete()`. 

But if the tests fail both `rollback()` and `complete()` are both called. 

If the tasks succeed then just `complete()` runs.

How do I have just `rollback()` called if the tests failed? Have I done something wrong or is it expected for both the rollback and completion tasks to be executed when the collection fails?

PHP5.6 on Mac OS Sierra

**Comment by greg-1-anderson** [comment]
Two changes are necessary:
- You have to call `completion()` / `rollback()` *before* you call `run()`. Calling it afterwards is too late, because the collection has already finished, and therefore will no longer call completion or rollback functions.
- You have to pass a function pointer to `completion()` / `rollback()`; calling the desired function will execute it immediately, and won't have any useful effect on the collection.

Something like this:
```
$collection = $this->collectionBuilder();
$collection->addTask(
$this->taskCodecept('vendor/bin/codecept')
->dir('release/application')
->test('functional')
->configFile('src/AppBundle')
->html("functional_output.html")
->rollbackCode([$this, 'rollbackMethod'])
->run();
```

**Comment by greg-1-anderson** [comment]
I [added some documentation on rollbackCode() and completionCode()](https://github.com/consolidation/Robo/commit/5d806c2f5f62275b2a592b393874e207f2f61cbe#diff-4d5cf345b804230d1260581bf0f96b21R116). This will go out the next time we push a release.
