### ISSUE TITLE
phpcodesniffer should not be pinned to exact version.

### ISSUE THREAD

**Issue by grasmash** [consolidation/Robo#547]
`squizlabs/php_codesniffer` is currently pinned to `2.7.0`. This makes dependency resolution difficult for projects using Robo PHP. It is a best practice to specify a minimum version, but not a specific version.

Two possible solutions:
* Move php_codesniffer from `require` to `require-dev` if possible
* Change `2.7.0` to `^2.7.0`

At present, I am encountering a conflict with the `drupal/coder` package, which requires `>=2.8.1 <3.0`

**Comment by greg-1-anderson** [comment]
The problem is that newer versions of php_codesniffer introduced more stringent PSR-2 compliance checking. Robo is now out of compliance according to php_codesniffer 2.8.0 and later. While this is, in fact, a compliance bug that has always been in Robo, and simply went unreported, we cannot fix it without bumping up to Robo version 2.x, as doing so would break backwards compatibility.

Yes, there is a b/c preserving fix, but it would require that we add a lot of classes to Robo.

A conflict with drupal/coder is inconvenient, though. We should consider which of our potential fixes are best.

Tagging @DavertMik

**Comment by greg-1-anderson** [comment]
Here is my proposal:

- Prepare a 1.1 release from what is on the master branch today.
- Fork a 1.x branch for backports to `master`.
- Change the branch alias for `master` to 2.x.
- Fix the PSR-2 compliance problems and tag a 2.0.0-alpha1 release.
- Backport anything sufficiently important from the `master` branch to the `1.x` branch.
- Plan on a 2.0.0 stable release in 3-6 months.

We tagged 1.0.0 close to 6 months ago, so a 6-month development cycle on 2.x would bring us close to a year between major releases, which is a pretty good cadence, IMO. We could always tag  it a little earlier if there is need.

I'll be the 1.x branch maintainer.

**Comment by grasmash** [comment]
Is the issue that when PHPCS sniffs Robo itself you don't want failure? If that's the case, you can just disable specific sniffs when you execute `phpcs`.

**Comment by greg-1-anderson** [comment]
@grasmash Yes, that is what @DavertMik suggested as well. Have you ever configured PHPCS before? I think the only think it is complaining about in the new version is `trait loadTasks` (should be `LoadTasks`).
