### ISSUE TITLE
Allow specifing minium robo version in Robofile

### ISSUE THREAD

**Issue by amenk** [consolidation/Robo#568]
### Steps to reproduce
* Have some robofile that needs a specific version of robo
* older version is installed
* run robo

### Expected behavior
* robo should say "minium robo version x.y.z is required"

### Actual behavior
* any kind of other error would appear

I am especially interested in this when bundling custom functionality to my personal robo.phar - but I think it is also useful for the core robo project.

Thoughts?

**Comment by greg-1-anderson** [comment]
I have considered things such as this; in addition, as we start considering making task plugins more robust, it might be useful for a RoboFile to be able to declare which plugins it needs, so that Robo might direct you to install the missing components.

I think that the way to go here it to give your RoboFile a `@hook init` method, and have that do any tests you need.

**Comment by amenk** [comment]
I am doing this not in my robo files

```

define('IROBO_MIN_VERSION', '1.2.2');

if (\Robo\Robo::APPLICATION_NAME != 'iRobo'
    || \Composer\Semver\Comparator::lessThan(\Robo\Robo::VERSION, IROBO_MIN_VERSION) > 0) {
	echo 'ERROR: This script needs iRobo (not only robo) version ' . IROBO_MIN_VERSION
	     . ' or later - download at http://irobo.imi.de/irobo.phar '. PHP_EOL;
	die(1);
}

**Comment by greg-1-anderson** [comment]
That looks reasonable.
