### ISSUE TITLE
askDefault doesn't work

### ISSUE THREAD

**Issue by goldquest** [consolidation/Robo#606]
### Steps to reproduce
- Make a custom task
- use Robo\Common\IO trait
- use $this->askDefault()
- Execute task

### Expected behavior
- Question gets asked in console

### Actual behavior
- Console waits for input, but Question is not shown

### System Configuration
MacOS,  php 7.0.4

**Comment by goldquest** [comment]
This seems to be the case for all IO functions.
Maybe I'm also just missing something, since I still can't really wrap my head around how to do things in robo 1.x....

**Comment by goldquest** [comment]
OK, on this site http://robo.li/extending/ under `TaskIO` it is stated, that I shouldn't `say` or `ask` in my tasks, to make them reusable, but I need to say, ask and yell and it is fine, since we are just building tasks for use with our drupal distribution. How am I supposed to do that with robo in 1.x? (And it is too much to put it in the Robofile)

**Comment by goldquest** [comment]
(Right now I am working on this file, if it helps: https://github.com/BurdaMagazinOrg/robo/blob/master/Task/Settings/EnsureSettingsFile.php, but I need to adapt the complete repo)

**Comment by greg-1-anderson** [comment]
If you don't want to write to the Task coding conventions, then why make a task at all? You may, if you prefer, just call `new MyClass()` in your RoboFile, construct the class as you wish, and run whatever sort of code you like. The class you linked to does not appear to aspire to be a task at all; you would probably be better off avoiding the task overhead and use a simple class.

If you do wish to create a reusable task, then you should follow the instructions in [Extending Robo](http://robo.li/extending/) (the page you linked to above) closely. One thing I noticed that you were not doing right was your task definition in your loadTasks.php file. If you simply call `new MyClass()` here, as was the convention in Robo 0.x, then Robo will not construct your task object fully. Follow the advice of the documentation, and [use the task method](http://robo.li/extending/#create-the-loadtasksphp-trait) in your loadTakss methods.

If you do this, it is not necessarily impossible for you to use `say` or `ask` in a task. You may need to explicitly `use IO`, since I think tasks no longer do so by default. Prompting for user in put in a task will make it harder to test, less convenient to use in a CI setting, and less convenient to re-use in other code that might not be running in interactive mode. Robo encourages scripts to collect all input before the first task is `run()` because this generally results in cleaner, better organized code. However, Robo won't stop you from doing this, as long as you ensure that your objects are constructed fully once instantiated.
