### ISSUE TITLE
Lay the groundwork for Robo plugins

### ISSUE THREAD

**Issue by ademarco** [consolidation/Robo#670]
## Motivation

Currently the only way to customize Robo behavior is to built your own standalone application as described
in [Robo as a Framework](http://robo.li/framework/).

This issue wants to explore possible ways for third-parties to manipulate the service container in order to allow advanced customization like: alternative command class discovery methods, custom plugin systems, and so on.

## Possible solution

A possible solution would be to fire events in `\Robo\Robo::configureContainer()` that will allow event subscribers to manipulate the container.

Additionally we should provide a way for subscribers to be discovered at run-time, so that third-parties would be able to manipulate the container by, for example, placing the subscriber class under a predefined namespace (e.g. discovery by naming-convention).

Parts of the solution outlined above can be found in the [European Commission's Task Runner](https://github.com/ec-europa/oe-task-runner) which is an example of "Robo as a framework" project.

The Task Runner above allows for [command classes to be auto-discovered](https://github.com/ec-europa/oe-task-runner#expose-custom-commands-as-php-classes) and commands to be [dynamically defined via YAML](https://github.com/ec-europa/oe-task-runner#expose-custom-commands-as-yaml-configuration) and it can achieve that by just taking control over the Robo Runner container.

The outlined solution would essentially remove the need for a custom application (e.g. "Robo as a Framework").

## Outline

The method described above could be implemented in the following way:

#### Step 1: Define an event for container manipulation

We would ideally create an event for container manipulation, like `\Robo\Events\AlterContainer` or similar, which will include the actual container for manipulation.

Additional events that will fire in other sensitive parts of the Robo Runner can also be created.

#### Step 2: Auto-discovery of event subscribers

In order to auto-discover event subscriber classes we should pass the Composer class loader to the runner, something like:

```php
<?php
...
    } else {
      $classLoader = require __DIR__.'/../vendor/autoload.php';
    }
}

$runner = new \Robo\Runner();
$runner->setSelfUpdateRepository('consolidation/robo');
$runner->setClassLoader($classLoader);
$statusCode = $runner->execute($_SERVER['argv']);
exit($statusCode);
```

Then, after that, we would collect event subscribers based on some sort of naming convention, say we will load all classes in PSR-4 that use the partial namespace `..\Robo\EventSubscribers\..`, something like: 

```php
<?php

    public function registerEventSubscribers(Container $container, ClassLoader $classLoader)
    {
        foreach ($classLoader->getPrefixesPsr4() as $baseNamespace => $directoryList) {
            $directoryList = array_filter($directoryList, function ($path) {
                return is_dir($path.'/Robo/EventSubscribers');
            });

            if (!empty($directoryList)) {
                $subscribers = $this->discoverSubscribers($directoryList, $baseNamespace);
                foreach ($subscribers as $subscriber) {
                    $container->get('eventDispatcher')->addSubscriber($subscriber);
                }
            }
        }
    }
```

The `registerEventSubscribers()` method above would be called at the end of `\Robo\Robo::configureContainer()`, right after that the default container is fully configured.

This means that third-parties libraries would just need to provide subscriber classes following that naming convention to be autloaded, like:

```
\My\Library\Robo\EventSubscribers\MySubscriber
```

#### Step 3: Fire events

The event in Step 1 will be fired after step two, allowing third-parties to hook into the container building process.

At this point third-parties can also provide their own plugin systems, altering how custom command classes are being discovered or providing dynamic commands via YAML.

I'll work on a POC in the upcoming days.

**Comment by ademarco** [comment]
\cc @greg-1-anderson @weitzman : the issue we discussed about in the Slack channel.

**Comment by greg-1-anderson** [comment]
As I said in slack, these ideas look really good.

Regarding plugins, it would be good if event subscribers and command plugins could be reconciled (https://github.com/consolidation/Robo/pull/604) so that there is only one kind of Robo plugin, and any given plugin may add either an event subscriber or a command file (or multiple of same). I don't know if there are other types of plugin classes we might anticipate, but bonus points for making the plugin capability discovery extensible. (I'm just talking about readable / well-factored code here, not a plugin-plugin. 😉  )

Regarding altering the container, at the moment, Robo does not support this because, by the time a RoboFile is loaded, most of the classes in the container have already been instantiated. Anyone who attempted to alter the container definition after objects were already instantiated would encounter inconsistent results. For objects that are always instantiated early (e.g. the logger), alterations would just be ignored. Worst case, though, is that changes to the Robo startup code could break existing plugins that were altering things in the container that, up to that point, were not previously instantiated at that point. This would cause a lot of angst and suffering.

To address this, and provide a mechanism that supports extending DI without suffering, I propose:

1. Make a new secondary DI container that starts out empty.
2. Call an `addToContainer($container)` method on each DI subscriber.
3. Call an `alterContainer($container)` method on each DI subscriber.
4. Add the container as a delegate of the primary Robo container.

If there were some Robo classes that we KNEW would never be instantiated during the Robo startup code (at least not in the current major version), then we could add those to the secondary DI container, and let DI subscribers modify those if they wished.

**Comment by ademarco** [comment]
I see, so initially we would have two types of plugins:

- Event subscribers: discoverable under `..\Robo\EventSubscribers\..`
- Commands files: discoverable under `..\Robo\Commands\..`

Looks a bit like Drupal 8 plugin architecture, right? Meaning we will have:

- A `EventSubscriberPluginManager` which uses a the namespacing discovery method described above (or another) and collects event subscribers
- A `CommandsPluginManager` which might use another discovery method to collect command files

But then we can have more than one "Plugin providers", meaning providers that return the same plugin type in different way, in this way the default plugin provider will return the default `RoboFile.php` and the "Namespace plugin provider" will collect plugin with another discovery method, in this way we kind of harmonize command discovery.

Looks a bit like what happen for Drupal 8 :)

About container delegation: I'm in 100%! So then all plugins (of the same type?) will share a delegate container, so that they will not bother the main one.

**Comment by greg-1-anderson** [comment]
Yeah, just one delegate container for all plugins.

Also, I'd rather not have two types of plugins, but rather one type of plugin that has two kinds of things provided by its autoloader, `..\Robo\EventSubscribers\..` and `..\Robo\Commands\..`. I think that's essentially what you were saying above, but wanted to clarify the terminology. When I say plugin, I mean a collection of php sources (and other files) with an autoloader -- like a Drupal "project". If you used "plugin" to mean something inside one of these projects, then we're on the same page.

**Comment by greg-1-anderson** [comment]
Oh, and I'm indifferent about the implementation of the manager(s), as long as it's sufficiently clean. An EventSubscriberPluginManager and a CommandsPluginManager would work fine, I think.

**Comment by ademarco** [comment]
As discussed with @greg-1-anderson in Slack channel we will focus on getting in only the command files discovery for now. After that this is merged in we will open a follow up issue where we investigate the need of an Event Subscriber plugin by describing some concrete use-cases and asking the community for feedback.
