### ISSUE TITLE
Global RoboFile

### ISSUE THREAD

**Issue by sagikazarmark** [consolidation/Robo#70]
It would be a good feature to have a "global" RoboFile (in home directory?) and have some common tasks used in many projects (eg. watching for changes in [src/lib] folder and running tests on change.

**Comment by brodkin** [comment]
We do this by keeping those tasks namespaced in a separate repository and then loading them into the Robofile via `use` statements. Doing it this way allows us to version the global tasks to ensure that changes to those tasks don't break our other builds.

**Comment by sagikazarmark** [comment]
That's great idea. I am going to try it out.

However my original intention was rather having commands in your environment.

Something like composer global package installation.

**Comment by brodkin** [comment]
Got it--definitely a different use case. For that, however, you could probably write a Robo project that could be included globally as you suggested. The trick would be that you couldn't use the `robo` executable. Instead you would need to write a wrapper script `myrobo` that would then execute `robo` in the context of your global project, forcing it to use that robofile. For portability you could then define your wrapper as a binary in composer.json so that anyone installing your project could just run `myrobo` and it would just work.

**Comment by sagikazarmark** [comment]
Yeah, nice trick as well. ;)

**Comment by greg-1-anderson** [comment]
See [script.robo](https://github.com/consolidation/Robo/blob/master/script.robo) for an example of writing a simple shell script using Robo.  The idea @brodkin describes above is now documented in [framework.md](https://github.com/consolidation/Robo/blob/master/docs/framework.md).
